### ISSUE TITLE
Change user display name

### ISSUE THREAD

**Issue by LNA** [SheNomads/tracker#23]
Should just be the users first name

**Comment by LNA** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HTRImdlD&#x2F;8-change-user-display-name"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Change user display name</a>

**Comment by goldstarwebs** [comment]
The auth hash returns a lot of information upon successful login (and user creation) via Facebook or Twitter.  For someone looking to work on this task, I came across this page which should be helpful:  [https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema](https://github.com/omniauth/omniauth/wiki/Auth-Hash-Schema)   You get back a lot of information (like first name) separately already, so perhaps save it into the User model in its own field?
